FROM node:16.9.1-buster as slate_node

WORKDIR /srv

RUN git clone https://github.com/Mermade/widdershins.git builder && \
    npm --prefix ./builder install -g widdershins

WORKDIR /srv/builder

RUN node widdershins --search false --language_tabs 'ruby:Ruby' 'python:Python' --summary project/swagger.yml -o project/swagger.md
