FROM node:16.9.1-buster as slate_node

ARG UID=1000
ARG GID=1000

WORKDIR /srv

RUN mkdir /srv/project && \
    git clone https://github.com/Mermade/widdershins.git builder && \
    npm --prefix ./builder install -g widdershins && \
    npm --prefix ./builder i

WORKDIR /srv/builder

COPY ./scripts/generate.sh .
